version: 1
ifc_schemas: ["IFC2X3", "IFC4", "IFC4x3"]

defaults:
  scope: elements
  when_missing_property: fail
  case_sensitive: false
  ignoredEntities: [IfcOpeningElement]

rules:
  - id: Identifikation
    title: Alle objekter skal have Identifikation
    targetEntities: [IfcElement]
    checks:
      - property: "KKU.Identifikation"
        required: true
        pattern: "^[A-Z]{1,}[0-9]{2}$"
        
  - id: Lokation
    title: Alle objekter skal have Lokation
    targetEntities: [IfcElement]
    checks:
      - property: "KKU.Lokation"
        required: true
        pattern: "^(L00|L10|L20|L21|L22|L23|L30|L40|L50)$"
